# Generated by Django 3.1.2 on 2021-11-10 17:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa machines')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Opis machines')),
                ('performance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wydajność machines')),
            ],
        ),
        migrations.CreateModel(
            name='number_of_elements_from_the_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_elements', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa zlecenia')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Opis zlecenia')),
                ('date_of_start', models.DateField(blank=True, null=True, verbose_name='Data rozpoczęcia zlecenia')),
                ('data_zakonczenia', models.DateField(blank=True, null=True, verbose_name='Data zakończenia zlecenia')),
                ('visible', models.BooleanField(default=True, verbose_name='Czy zlecenie jest visible?')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa produktu')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Opis produktu')),
                ('item_mass', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Masa produktu')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sensor', max_length=50, verbose_name='Nazwa czujnika')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Opis czujnika')),
                ('rodzaj_czujnika', models.CharField(choices=[('ciagly', 'Licznik(pomiar ciągły)'), ('chwilowy', 'Termometr(pomiar chwilowy)'), ('masy_ciagly', 'Waga(pomiar sumowany)'), ('masy_chwilowy', 'Waga(pomiar chwilowy)')], max_length=50, verbose_name='Rodzaj czujnika')),
                ('przykladowy_odczyt', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Przykładowa wartość odczytu')),
            ],
        ),
        migrations.CreateModel(
            name='sensor_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_czujnika', models.CharField(max_length=10)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('wartosc_zmierzona', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='the_number_of_elements_from_the_order_to_pass_through_the_machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_per_element', models.DurationField(blank=True, null=True, verbose_name='Czas na jeden element?')),
                ('id_machines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produkcja.machine')),
                ('id_zlecenia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produkcja.number_of_elements_from_the_order')),
            ],
        ),
        migrations.AddField(
            model_name='number_of_elements_from_the_order',
            name='id_Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produkcja.order'),
        ),
        migrations.AddField(
            model_name='number_of_elements_from_the_order',
            name='id_Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produkcja.product'),
        ),
        migrations.CreateModel(
            name='Location_sensor_in_machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_placement', models.CharField(choices=[('wejscia', 'Sensor na wejściu machines'), ('wewnetrzny', 'Sensor oprzyrządowania machines'), ('wyjsca', 'Sensor na wyjściu machines')], max_length=50, verbose_name='Położenie czujnika w maszynie')),
                ('prefix', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prefix wartości')),
                ('suffix', models.CharField(blank=True, max_length=50, null=True, verbose_name='Suffix wartości')),
                ('id_Machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produkcja.machine')),
                ('id_Sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produkcja.sensor')),
            ],
        ),
    ]
