# Generated by Django 3.2.8 on 2021-10-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_czujnika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_czujnika', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now=True)),
                ('wartosc_zmierzona', models.CharField(max_length=10)),
            ],
        ),
    ]
