# Generated by Django 3.2.8 on 2021-10-28 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0002_log_czujnika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_czujnika',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
