# Generated by Django 3.2.8 on 2021-10-28 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0003_alter_log_czujnika_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_czujnika',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
