# Generated by Django 3.2.8 on 2021-11-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0004_alter_log_czujnika_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='zlecenie',
            name='widoczne',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='maszyna',
            name='nazwa',
            field=models.CharField(max_length=50, verbose_name='Nazwa maszyny'),
        ),
        migrations.AlterField(
            model_name='maszyna',
            name='opis',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Opis maszyny'),
        ),
        migrations.AlterField(
            model_name='maszyna',
            name='wydajnosc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Wydajność maszyny'),
        ),
    ]
