# Generated by Django 3.2.8 on 2021-11-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0007_auto_20211107_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilosc_elementow_ze_zlecenia_ma_przejsc_przez_maszyne',
            name='time_per_element',
            field=models.DurationField(blank=True, null=True, verbose_name='Czas na jeden element?'),
        ),
    ]
