# Generated by Django 3.2.8 on 2021-11-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0008_alter_ilosc_elementow_ze_zlecenia_ma_przejsc_przez_maszyne_time_per_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zlecenie',
            name='data_rozpoczecia',
            field=models.DateField(blank=True, null=True, verbose_name='Data rozpoczęcia zlecenia'),
        ),
        migrations.AlterField(
            model_name='zlecenie',
            name='data_zakonczenia',
            field=models.DateField(blank=True, null=True, verbose_name='Data zakończenia zlecenia'),
        ),
    ]
