# Generated by Django 3.1.2 on 2021-11-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0010_auto_20211108_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zlecenie',
            name='data_rozpoczecia',
        ),
        migrations.RemoveField(
            model_name='zlecenie',
            name='data_zakonczenia',
        ),
    ]
