# Generated by Django 3.1.2 on 2021-11-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0011_auto_20211108_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='zlecenie',
            name='data_rozpoczecia',
            field=models.DateField(blank=True, null=True, verbose_name='Data rozpoczęcia zlecenia'),
        ),
        migrations.AddField(
            model_name='zlecenie',
            name='data_zakonczenia',
            field=models.DateField(blank=True, null=True, verbose_name='Data zakończenia zlecenia'),
        ),
    ]
