# Generated by Django 3.1.2 on 2021-11-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0012_auto_20211108_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='czujnik',
            name='nazwa',
        ),
        migrations.RemoveField(
            model_name='czujnik',
            name='opis',
        ),
        migrations.RemoveField(
            model_name='czujnik',
            name='przykladowy_odczyt',
        ),
    ]
