# Generated by Django 3.1.2 on 2021-11-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0014_auto_20211109_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czujnik',
            name='nazwa',
            field=models.CharField(default='Czujnik', max_length=50, verbose_name='Nazwa czujnika'),
        ),
    ]
