# Generated by Django 3.1.2 on 2021-11-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produkcja', '0015_auto_20211109_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='czujnik',
            old_name='polozenie_czujnika',
            new_name='rodzaj_czujnika',
        ),
    ]
